### ISSUE TITLE
VehicleStatus Help

### ISSUE THREAD

**Issue by ryanbuckner** [edent/BMW-i-Remote#15]
I'm able to successfully GET the list of vehicles in the account and POST a few instructions like "DOOR_LOCK" and "CLIMATE_NOW".

When trying to send a GET for Vehicle Status using the following code I receive an error and can't get past it. Hoping you can help. I'm in the US using ROOT_URL     = "https://b2vapi.bmwgroup.us/webapi"

CODE: 
`
print "\nStatus"
    status = c.call("/user/vehicles/{}/status".format(car['vin']))['vehicleStatus']
    for k,v in status.items():
        print "  ", k, " : ", v
`

ERROR: 
`
Status
Traceback (most recent call last):
  File "./bmw.py", line 153, in <module>
    main()
  File "./bmw.py", line 147, in main
    status = c.call("/user/vehicles/{}/status".format(car['vin']))['vehicleStatus']
KeyError: 'vehicleStatus'
`

**Comment by ryanbuckner** [comment]
By the way, this is working now. Strangely with my 535i in the US, I only get 3 items returned by the JSON.
