### ISSUE TITLE
Vehicle status not working.

### ISSUE THREAD

**Issue by bdwilson** [edent/BMW-i-Remote#9]
Any thoughts on why this isn't working?  It has the VIN in vehicle info, but can't pull status info.  I see the status info within Charles Proxy when I use the app. 

```
 $ PYTHONWARNINGS="ignore:Unverified HTTPS request" ./bmw.py

Vehicle info
   sendPoi  :  ACTIVATED
   lastDestinations  :  SUPPORTED
   countryCode  :  V2-US
   color  :  LAURUSGRAU MET. M.AKZENT
   vin  :  WBY1Z4xxxxxxxxx
   climateControl  :  NOT_SUPPORTED
   climateNow  :  ACTIVATED
   hasAlarmSystem  :  True
   dealer  :  {u'postalCode': u'12345', u'city': u'City', u'street': u'Address', u'name': u'My BMW', u'country': u'US'}
   remote360  :  NOT_SUPPORTED
   smartSolution  :  NOT_SUPPORTED
   vehicleFinder  :  ACTIVATED
   colorCode  :  B79
   lscType  :  I_LSC_IMM
   rangeMap  :  RANGE_POLYGON
   statisticsCommunityEnabled  :  False
   hornBlow  :  ACTIVATED
   doorUnlock  :  NOT_SUPPORTED
   driveTrain  :  BEV_REX
   hub  :  HUB_US
   brand  :  BMW_I
   statisticsAvailable  :  True
   yearOfConstruction  :  2015
   climateFunction  :  AIRCONDITIONING
   supportedChargingModes  :  [u'AC_LOW', u'AC_HIGH', u'DC']
   doorLock  :  ACTIVATED
   bodytype  :  I01
   lightFlash  :  ACTIVATED
   intermodalRouting  :  AVAILABLE
   chargeNow  :  NOT_SUPPORTED
   model  :  I3 +REX
   onlineSearchMode  :  MAP
   chargingControl  :  WEEKLY_PLANNER

Vehicle status
Traceback (most recent call last):
  File "./bmw.py", line 155, in <module>
    main()
  File "./bmw.py", line 149, in main
    status = c.call("/user/vehicles/{}/status".format(car['vin']))['vehicleStatus']
KeyError: 'vehicleStatus'
```

**Comment by edent** [comment]
Are you using the right server? I assume you've an American vehicle?

Also, are you registered on Connected Drive both in app & car?

**Comment by bdwilson** [comment]
I'm using .com; the first data is valid for my vehicle info, so that makes me think the server is OK.  If I change to .us, then not even vehicle info works.  

Yes, App works as it should.

**Comment by bdwilson** [comment]
You were right; I changed to .us and both work.  It wasn't working before because it was using the cached session token.  I used curl to get a new session token for the new domain and now things work as they should.  Thx!
